= Anypoint MQ Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint MQ is a multi-tenant, cloud messaging service that enables customers to perform advanced asynchronous messaging scenarios between their applications. Anypoint MQ is fully integrated with Anypoint Platform, offering role-based access control, client management, and connectors.

++++
include::_partials/mq-overview-video.html[]
++++

Anypoint MQ does not support use with CloudHub Insight or Anypoint Monitoring. Instead, you can use the xref:mq-usage.adoc[Anypoint MQ usage graphs] to access usage information. You can view the current and past usage, including consumed data, API requests, and the total number of messages received. You can also use the xref:mq-apis.adoc#mqstatapi[Anypoint MQ Stats API] to perform statistical analysis of queue performance.


== Anypoint MQ Workflow

These are the high-level steps to use Anypoint MQ. This workflow is described in the xref:mq-tutorial.adoc[Anypoint MQ Tutorial].

Install and configure Anypoint MQ:

. Log in to Anypoint Platform using your Enterprise Mule credentials, and click *MQ*.
. Click *Access Management*, then *Users* or *Roles* to create an Anypoint MQ user or role.
. From *MQ*, create a xref:mq-queues.adoc[queue], xref:mq-exchanges.adoc[message exchange], or a xref:mq-queues.adoc#fifoqueues[FIFO queue].
. Click a queue or message exchange name in the detail to access the Message Sender to send messages to a queue or message exchange, and to use the Message Browser to get messages from a queue.
. From *MQ*, click *Client Apps* to register an app. You can view the client app ID and client secret for the app.

In Anypoint Studio:

. Install the Anypoint MQ connector using Anypoint Exchange.
. Create a new Mule project with needed building blocks, such as an HTTP connector, Anypoint MQ connector, Set Payload, and a Logger.
. Configure the Anypoint MQ connector and provide the client app ID and client secret of the app.
. Set the Anypoint MQ connector operation to publish or consume messages, or to accept (ACK) or not accept (NACK) a message. See xref:connectors::anypoint-mq/3.x/anypoint-mq-connector.adoc[Anypoint MQ Connector 3.x for Mule 4].
//
// Alternatively, Anypoint MQ can provide xref:mq-ack-mode.adoc[automatic Acknowledgment Mode]. If you set the Operation to publish, set the Destination to the name of a queue or message exchange that you created in Anypoint Platform. If you sent the Operation to consume, specify the name of a queue from which you want to receive messages.
. Run the Mule app.

Test the queue:

. Use a REST client such as curl or Postman to send or receive a message.
+
The Anypoint MQ app sends the string as a message to the queue or message exchange you specified.
+
. View your message in a browser or the Studio console.

== See Also

* xref:mq-understanding.adoc[Anypoint MQ Terminology]
* xref:mq-connectors.adoc[Anypoint MQ Connectors]
* xref:mq-faq.adoc[Anypoint MQ FAQ]
* xref:release-notes::mq/mq-release-notes.adoc[Anypoint MQ Release Notes]
* xref:access-management::audit-logging.adoc#to-query-audit-logging-for-anypoint-mq[Anypoint MQ Audit Logging]
* xref:mq-queues.adoc#fifoqueues[FIFO Queues]
