= Anypoint MQ Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint MQ is a multi-tenant, cloud-based message queuing service for exchanging data asynchronously between your applications. 
The Anypoint MQ messaging broker enables applications to communicate by publishing a Mule message to a queue so that another app can consume the message.

Anypoint MQ is fully integrated with Anypoint Platform and provides the same management capabilities.
Integration with Access Management enables you to specify environments and business groups for 
role-based access control and support for connected apps.

The following spotlight video gives an overview of Anypoint MQ:

++++
include::_partials/mq-overview-video.html[]
++++



Anypoint MQ supports hybrid use cases, IoT in which you collect data from different devices, and a REST API you can use with device applications.
You can also use Anypoint MQ with other app frameworks such as node.js to communicate to queues.

Anypoint MQ:

* Provides fully hosted and managed xref:mq-queues.adoc[queues] and 
xref:mq-exchanges[message exchanges] in the cloud.


* Supports using connected apps to authenticate with Anypoint Platform using APIs.
+
See xref:mq-connected-apps.adoc[].
* Supports large payloads, encryption, queuing, and publish/subscribe (pub/sub) paradigms.
* Enables you to easily connect to non-Mule applications using the REST API.
* Provides Anypoint Studio access, which makes the process of leveraging your queues and message exchanges as simple as drag, drop, and configure.
* Displays usage statistics on the number of messages and API requests so you can manage peak usage and subscription parameters.
* Provides dead-letter queue capability for undeliverable messages.
* Enables you to delay message delivery at the queue and message level.
* Provides the ability to group messages in FIFO queues.


== Anypoint MQ Features

Anypoint MQ includes these features:

* *Queues and Message Exchanges*
+
Send messages to queues, pull messages from queues, create a message exchange to perform pub/sub scenarios to send a message to multiple queues.
* *Management Console*
+
Monitor queue statistics, purge queues, and see how many messages are in flight using the management console.
* *Anypoint MQ Connector*
+
Send and receive messages from any Mule app, whether it's deployed in CloudHub or used in a hybrid scenario and deployed on-premises.
* *Usage Information*
+
Organization administrators or owners can view the current and past months' usage, including the total number of messages and API requests. You access this information from the *Access Management* page. For more information, see xref:mq-usage.adoc[Anypoint MQ Usage Information].
* *REST API*
+
Use the REST API to easily communicate with non-Mule applications.
* *Environments and role-based access control*
+
Anypoint MQ is fully integrated with Access Management, allowing you to specify different environments for your queues, who can access each environment, and what they can do within each environment.
* *Client Management*
+
Create connected application tokens.
* *Large Payloads*
+
Anypoint MQ supports payloads up to 10 MB.
+
// MQ Payload Conversion
include::partial$mq-big-payload.adoc[tag=mqPayloadConvert]

[[disaster-recovery]]
* *Disaster Recovery*
+
Within each region, Anypoint MQ services deploy to multiple availability zones (AZs) to provide high availability (HA). If service in one availability zone goes down, the Anypoint MQ service operates normally in that region. If all availability zones go down in a region, the Anypoint MQ service is unavailable in that region until at least one of the availability zones comes back up. Because the storage solution for Anypoint MQ is durable, messages that were already in the Anypoint MQ system before service was interrupted are retained.

[[usage-statistics]]
* *Usage Statistics*
+
View a chart indicating how much data and how many API requests have been consumed, and how many message units were received.
The chart provides current and past usage, including consumed data, API requests, and the total number of messages received.
See xref:mq-usage.adoc[] to access usage information.
+
You can also use the xref:mq-apis.adoc#mqstatapi[Anypoint MQ Stats API] to perform statistical analysis of queue performance.
+
[NOTE]
Anypoint MQ does not support use with CloudHub Insight or Anypoint Monitoring.


== Queue Features


[[delay-queues]]
* *Delay Queues*
+
With delay queues, you can postpone the delivery of new messages to a queue for a specified period. Consumers can't see messages sent to a delay queue for the duration of the delay period. The minimum delay for a queue is 0 seconds. The maximum is 15 minutes.
+ 
If you change the queue delay for:

** Standard queues, the setting change doesn't affect messages in the queue.
** FIFO queues, the setting change is retroactive to all messages in the queue.

+
You can override the default queue delay for a particular message in a standard queue only.

[[delay-messages]]
* *Delayed Message Delivery*
+
For messages in a standard queue, you can postpone the delivery of a particular message to the queue for a specified period. Consumers can't see messages sent with delivery delay for the duration of the delay period. The minimum delivery delay for a message is 0 seconds. The maximum is 15 minutes.
+ 
Delayed delivery is not supported for individual messages in a FIFO queue.

[[message-groups]]
* *Message Groups*
+
In FIFO queues, you can assign messages to a message group to enable multiple consumers to process messages from a single FIFO queue.

[[encrypt-queue]]
* *Encrypted Queues*
+
Messages in queues data can optionally be encrypted, enabling companies to be compliant with their data at rest policies. 
//Shared Encryption
include::partial$mq-faq.adoc[tag=faqEncryption]
+
include::partial$mq-faq.adoc[tag=faqEncryptionQandEx]







== Glossary

ACK/NACK::
* ACK - An app receives a message and Anypoint MQ deletes the message. 
* NACK - An app does not receive a message and Anypoint MQ does not delete the message.

+
For more information, see xref:anypoint-mq-connector::anypoint-mq-ack.adoc[ACK and NACK Operations].
Binding::
+
Enables pub/sub apps to bridge the simple pub/sub structure and use point-to-point features, such as sending a message to specific applications.
Bindings identify which queues comprise a message exchange.
In Anypoint Platform, by specifying which message queues are bound to a message exchange, Anypoint MQ creates and manages the bindings for you.
+
// Max Msg Exchange 
include::partial$mq-msg-exchange.adoc[tag=msgExchangeMax]
include::partial$mq-msg-exchange.adoc[tag=msgExchangeMaxRouting]
Dead Letter Queue (DLQ)::
A queue that stores undeliverable messages from other queues.
+
See xref:mq-queues.adoc#dead-letter-queues[Dead Letter Queues]
Destination::
A message exchange or queue. Applications register to a destination and publish messages to the destination. Applications subscribe to a destination to receive a message. Anypoint MQ lets you configure Destinations by creating or maintaining queues or message exchanges.
You configure destinations in Anypoint Studio using Anypoint MQ Connector.
Durable message::
A message that persists until its indicated client receives it.
Duration::
Messages can persist in flight for up to 2 weeks after which messages older than 2 weeks are deleted. 
In Flight::
Messages that are: 
* Received by a queue, but not deleted
* Awaiting acknowledgment (ACK) or not acknowledgment (NACK)
* Not returned to the queue due to an expired *Default Acknowledgement Timeout* (time-to-live) setting

+
--
In-flight messages are not visible to other consumers. 

Anypoint MQ supports up to 120,000 in-flight messages per queue for standard (non-FIFO) queues. FIFO queues can have up to 10 in-flight messages in each message group.
--
In Queue::
Messages that have been sent.
+
Anypoint MQ supports unlimited messages in queue for both standard and FIFO queues.
Lock ID::
A lock that lets an app read a queue exclusively. Anypoint MQ provides the lock when an app acknowledges a message from a queue. A locked message does not block other messages to be read. The lock makes a message unavailable to other applications while locked.
Message::
Serializable xref:mule-runtime::about-mule-message.adoc[Mule Message] content that applications send and receive so that the applications can communicate with each other.
Message Exchange::
A pub/sub message source with multiple outputs. Applications register to subscribe to messages that the message exchange publishes.
On-premises::
Mule runtime that runs on a computer in your organization.
Payload::
The message content, which can be text, JSON, or CSV (comma-separated values).
Point-to-Point::
A pattern that allows an app to send a message that only a single app can receive.
Pub/Sub (Publish/Subscribe)::
A pattern that distributes messages to multiple consumers.
Publisher::
An app that sends messages to Anypoint MQ.
Queue::
A point-to-point message storage area that holds a message that a client receives.
Subscriber::
An app that receives messages from Anypoint MQ.


== See Also

* xref:mq-connectors.adoc[Anypoint MQ Connectors]
* xref:mq-faq.adoc[Anypoint MQ FAQ]
* xref:mq-release-notes.adoc[Anypoint MQ Release Notes]
* xref:access-management::audit-logging.adoc#to-query-audit-logging-for-anypoint-mq[Anypoint MQ Audit Logging]
