= Anypoint MQ Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint MQ is a multi-tenant, cloud messaging service that enables customers to perform advanced asynchronous messaging scenarios between their applications. Anypoint MQ is fully integrated with Anypoint Platform, offering role-based access control, client management, and connectors.

The following spotlight video gives an overview of Anypoint MQ:

++++
include::_partials/mq-overview-video.html[]
++++

Anypoint MQ does not support use with CloudHub Insight or Anypoint Monitoring. Instead, you can use the xref:mq-usage.adoc[Anypoint MQ usage graphs] to access usage information. You can view the current and past usage, including consumed data, API requests, and the total number of messages received. You can also use the xref:mq-apis.adoc#mqstatapi[Anypoint MQ Stats API] to perform statistical analysis of queue performance.


== Anypoint MQ Workflow

These are the high-level steps to use Anypoint MQ. This workflow is described in the xref:mq-tutorial.adoc[Anypoint MQ Tutorial].

. In Anypoint Platform, configure Anypoint MQ:
.. Log in to Anypoint Platform using your Enterprise credentials, and click *MQ*.
.. Click *Access Management*, then *Users* or *Roles* to create an Anypoint MQ user or role.
.. From *MQ*, create a xref:mq-queues.adoc[queue], xref:mq-exchanges.adoc[message exchange], or a xref:mq-queues.adoc#fifoqueues[FIFO queue].
.. Access the *Message Sender* page to send messages to a queue or message exchange and the *Message Browser* page to get messages from a queue.
.. Configure a xref:mq-connected-apps.adoc[connected app] to get an ID and secret to configure Anypoint Connector for MQ (Anypoint MQ Connector).

. In Anypoint Studio, configure Anypoint MQ Connector in your Mule app:
.. Install Anypoint MQ Connector using Anypoint Exchange.
.. Create a new Mule project with required building blocks, such as an Anypoint Connector for HTTP (HTTP Connector), Anypoint MQ Connector, Set Payload, and a Logger.
.. Configure Anypoint MQ Connector and provide the ID and secret of the connected app.
.. Set the Anypoint MQ Connector operation to publish or consume messages, or to accept (ACK) or not accept (NACK) a message.
+
For information about Anypoint MQ Connector, see xref:anypoint-mq-connector::index.adoc[Anypoint MQ Connector 4.x for Mule 4].
//
// Alternatively, Anypoint MQ can provide xref:mq-ack-mode.adoc[automatic Acknowledgment Mode]. If you set the Operation to publish, set the Destination to the name of a queue or message exchange that you created in Anypoint Platform. If you sent the Operation to consume, specify the name of a queue from which you want to receive messages.
.. Run the Mule app.

. Test the queue:
.. Use a REST client such as `curl` or Postman to send or receive a message.
+
Anypoint MQ sends the string as a message to the queue or message exchange you specified.
+
.. View your message in a browser or the Studio console.

[[mq-in-govcloud]]
== Anypoint MQ in MuleSoft Government Cloud

All features of Anypoint MQ are supported in MuleSoft Government Cloud with the following exceptions:

* Unencrypted queues are not supported.
+
All queues are encrypted. 
When xref:mq-queues.adoc#create-a-queue[creating a queue], the *Encryption* option is disabled and defaults to selected.
* xref:mq-client-apps.adoc[Client apps] are not supported.
+
Use 
xref:mq-connected-apps.adoc[connected apps] instead.
* Anypoint Connector for Anypoint MQ versions earlier than 4.x are not supported.
+
Using connected apps with Anypoint MQ requires xref:anypoint-mq-connector::index.adoc[Anypoint MQ Connector 4.x for Mule 4].
* The following REST APIs in the Anypoint MQ Stats API are not supported:
+
--
** https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-stats/minor/1.0/console/method/%23322/[Get usage metrics for an org]
** https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-stats/minor/1.0/console/method/%23383/[Get usage metrics for an environment within an org]
--
+
You can use Anypoint MQ Stats API to retrieve metrics for queues and exchanges.
See 
xref:mq-apis.adoc#mqstatapi[Anypoint MQ Stats API].


== See Also

* xref:mq-understanding.adoc[Anypoint MQ Terminology]
* xref:mq-connectors.adoc[Anypoint MQ Connectors]
* xref:mq-faq.adoc[Anypoint MQ FAQ]
* xref:release-notes::mq/mq-release-notes.adoc[Anypoint MQ Release Notes]
* xref:access-management::audit-logging.adoc#to-query-audit-logging-for-anypoint-mq[Anypoint MQ Audit Logging]
* xref:mq-queues.adoc#fifoqueues[FIFO Queues]
