= Anypoint MQ Glossary
:page-aliases: mq-understanding.adoc

ACK/NACK::
Operations that specify the following:
+
--
* ACK operation - An app receives a message, and Anypoint MQ deletes the message. 
* NACK operation - An app does not receive a message, and Anypoint MQ doesn't delete the message.
--
+
For information, see xref:anypoint-mq-connector::anypoint-mq-ack.adoc[ACK and NACK Operations].
Binding::
+
A method for specifying a set of standard queues that form a message exchange, enabling apps to send messages to multiple queues.
+
When you specify which message queues are bound to a message exchange, Anypoint MQ creates and manages the bindings for you.
+
For information, see xref:mq-exchanges.adoc[].

[[dead-letter-queues]]
Dead Letter Queue (DLQ)::
A queue that stores undeliverable messages from other queues.
+
For information, see xref:mq-queues.adoc#dead-letter-queues[Dead Letter Queues].

[message-lock-ttl]
Default Acknowledgement Timeout::
The period that a message remains unacknowledged before being returned to the queue, for example, if a server fails or if flow processing takes too long and times out.

[[delay-queue]]
Delay Queue::
A queue that postpones delivery of new messages for a specified period.
+
Consumers can't see messages sent to a delay queue for the delay duration.
The minimum delay for a queue is 0 seconds. The maximum is 15 minutes.
+ 
If you change the queue delay for a:
+
--
** Standard queue, the setting change doesn't affect messages in the queue.
** FIFO queue, the setting change is retroactive to all messages in the queue.
--
+
You can override the default queue delay for a particular message in a standard queue only.

[[delay-messages]]
Delayed Message Delivery::
A setting that specifies how long to postpone delivery of a particular message to a standard queue.
+
Consumers can't see messages sent with delivery delay for the delay duration.
The minimum delivery delay for a message is 0 seconds.
The maximum is 15 minutes.
+ 
FIFO queues don't support delayed delivery for individual messages.
Destination::
A message exchange or queue.
+
Applications register to a destination and publish messages to that destination. Applications subscribe to a destination to receive a message. Anypoint MQ lets you configure destinations by creating or maintaining queues or message exchanges.
You configure destinations in Anypoint Studio using Anypoint MQ Connector.
Durable Message::
A message that persists until its target client receives it.
Duration::
The period during which messages can persist in flight (for up to two weeks), after Anypoint MQ deletes them.
[[encrypt-queue]]
Encrypted Queue::
A queue that is encrypted, enabling companies to comply with their data at rest policies.
include::partial$mq-encrypt-queue.adoc[tag=mqEncryptQueue]
+
//Shared Encryption
include::partial$mq-faq.adoc[tag=faqEncryption]
+
include::partial$mq-faq.adoc[tag=faqEncryptionQandEx]

[[failover]]
Failover::
A feature that, when enabled for standard queues, assigns a fallback queue in a fallback region.
If an application can't reach the Anypoint MQ server in the primary region, the connector automatically diverts message processing to the fallback region.
+
For information, see xref:mq-failover.adoc[].

[[fallback-queue]]
Fallback Queue::
A queue that Anypoint MQ automatically creates in a fallback region when failover is enabled for a standard queue.
// Fallback queues aren't configurable by end users
include::partial$mq-failover.adoc[tag=fallbackQnotConfig]
+
For information, see xref:mq-failover.adoc[].

[[fallback-region]]
Fallback Region::
A region that Anypoint MQ automatically assigns to a fallback queue when failover is enabled for a standard queue.
// Fallback queues aren't configurable by end users
include::partial$mq-failover.adoc[tag=fallbackQnotConfig]
+
For information, see xref:mq-failover.adoc[].

[[fifo-queues]]
FIFO Queue::
A queue that processes messages first-in, first-out (FIFO), ensuring message ordering for applications in which the order of messages must be strictly preserved and enforced.
+
For information, see xref:mq-queues.adoc#fifo-queues[FIFO Queues].

In-Flight::
Messages that are any of the following states: 
+
--
* Received by a queue, but not deleted
* Awaiting acknowledgment (ACK) or not acknowledgment (NACK)
* Not returned to the queue due to an expired *Default Acknowledgement Timeout* (time-to-live) setting
--
+
In-flight messages are not visible to other consumers. 
+
Anypoint MQ supports up to 120,000 in-flight messages per queue for standard (non-FIFO) queues.
FIFO queues can have up to 10 in-flight messages in each message group.

In Queue::
Messages that have been sent.
+
Anypoint MQ supports unlimited messages in queue for both standard and FIFO queues.
Lock ID::
An identifier that allows only a single app to read a queue.
Anypoint MQ provides the lock when an app acknowledges a message from a queue.
Message::
Serializable xref:mule-runtime::about-mule-message.adoc[Mule Message] content that applications send and receive so that they can communicate with each other.
Message Exchange::
A pub/sub message source with multiple outputs. Applications register to subscribe to messages that the message exchange publishes.
+
For information, see xref:mq-exchanges.adoc[].
[[message-groups]]
Message Groups::
An assignment of specific messages to a group, enabling multiple consumers to process messages from a single FIFO queue.
+
For information, see xref:mq-queues.adoc#fifo-queues-msg-groups[FIFO Queues and Message Groups].
Message-Routing Rules::
Rules that you configure on a message exchange binding to route a subset of the messages published to an exchange to a specific queue.
On-premises::
Mule runtime that runs on a computer in your organization.
Payload::
The message content, which can be text, JSON, or CSV (comma-separated values).
Point-to-Point::
A pattern that allows an app to send a message that only a single app can receive.
Pub/Sub (Publish/Subscribe)::
A pattern that distributes messages to multiple consumers.
Publisher::
An app that sends messages to Anypoint MQ.
Queue::
A point-to-point message storage area that holds a message that a client receives.
+
For information, see xref:mq-queues.adoc[].
Subscriber::
An app that receives messages from Anypoint MQ.
[[message-ttl]]
TTL (time-to-live)::
How long the message stays in a queue before Anypoint MQ expires and removes it from the queue.
+
Each queue has a message time-to-live (TTL).
+
include::partial$mq-ttl.adoc[tag=msgTTLchange]

== See Also

* xref:index.adoc[]
* xref:mq-faq.adoc[]
