= Anypoint MQ Glossary
:page-aliases: mq-understanding.adoc

ACK/NACK operations::
+
--
* ACK operation - An app receives a message and Anypoint MQ deletes the message. 
* NACK operation - An app does not receive a message and Anypoint MQ does not delete the message.
--
+
For information, see xref:anypoint-mq-connector::anypoint-mq-ack.adoc[ACK and NACK Operations].
Binding::
+
Enables pub/sub apps to bridge the simple pub/sub structure and use point-to-point features, such as sending a message to specific applications.
Bindings identify which queues form a message exchange.
In Anypoint Platform, by specifying which message queues are bound to a message exchange, Anypoint MQ creates and manages the bindings for you.
+
For information, see xref:mq-exchanges.adoc[].

[[dead-letter-queues]]
Dead Letter Queue (DLQ)::
A queue that stores undeliverable messages from other queues.
+
For information, see xref:mq-queues.adoc#dead-letter-queues[Dead Letter Queues].

[message-lock-ttl]
Default Acknowledgement Timeout::
How long a message remains unacknowledged before being returned to the queue, for example, if a server fails or if flow processing takes too long and times out.

[[delay-queues]]
Delay Queues::
+
With delay queues, you can postpone the delivery of new messages to a queue for a specified period.
Consumers can't see messages sent to a delay queue for the duration of the delay period.
The minimum delay for a queue is 0 seconds. The maximum is 15 minutes.
+ 
If you change the queue delay for a:
+
--
** Standard queue, the setting change doesn't affect messages in the queue.
** FIFO queue, the setting change is retroactive to all messages in the queue.
--
+
You can override the default queue delay for a particular message in a standard queue only.

[[delay-messages]]
Delayed Message Delivery::
+
For messages in a standard queue, you can postpone the delivery of a particular message to the queue for a specified period. Consumers can't see messages sent with delivery delay for the duration of the delay period.
The minimum delivery delay for a message is 0 seconds.
The maximum is 15 minutes.
+ 
Delayed delivery is not supported for individual messages in a FIFO queue.
Destination::
A message exchange or queue. Applications register to a destination and publish messages to that destination. Applications subscribe to a destination to receive a message. Anypoint MQ lets you configure destinations by creating or maintaining queues or message exchanges.
You configure destinations in Anypoint Studio using Anypoint MQ Connector.
Durable message::
A message that persists until its target client receives it.
Duration::
Messages can persist in flight for up to two weeks, after which they are deleted.
[[encrypt-queue]]
Encrypted Queues::
+
Messages in queues data can optionally be encrypted, enabling companies to comply with their data at rest policies. 
//Shared Encryption
include::partial$mq-faq.adoc[tag=faqEncryption]
+
include::partial$mq-faq.adoc[tag=faqEncryptionQandEx]


[[fifo-queues]]
FIFO Queues::
+
For applications in which the order of messages must be strictly preserved and enforced, Anypoint MQ provides first-in, first-out (FIFO) processing to ensure message ordering.
+
For information, see xref:mq-queues.adoc#fifo-queues[FIFO Queues].

In Flight::
Messages that are any of the following: 
+
--
* Received by a queue, but not deleted
* Awaiting acknowledgment (ACK) or not acknowledgment (NACK)
* Not returned to the queue due to an expired *Default Acknowledgement Timeout* (time-to-live) setting
--
+
In-flight messages are not visible to other consumers. 
+
Anypoint MQ supports up to 120,000 in-flight messages per queue for standard (non-FIFO) queues.
FIFO queues can have up to 10 in-flight messages in each message group.

In Queue::
Messages that have been sent.
+
Anypoint MQ supports unlimited messages in queue for both standard and FIFO queues.
Lock ID::
A lock that allows only a single app to read a queue.
Anypoint MQ provides the lock when an app acknowledges a message from a queue.
Message::
Serializable xref:mule-runtime::about-mule-message.adoc[Mule Message] content that applications send and receive so that they can communicate with each other.
Message Exchange::
A pub/sub message source with multiple outputs. Applications register to subscribe to messages that the message exchange publishes.
+
For information, see xref:mq-exchanges.adoc[].
[[message-groups]]
Message Groups::
+
You can enable multiple consumers to process messages from a single FIFO queue by assigning messages to a message group.
+
For information, see xref:mq-queues.adoc#fifo-queues-msg-groups[FIFO Queues and Message Groups].
Message-Routing Rules::
Rules that you configure on a message exchange binding to route a subset of the messages published to an exchange to a specific queue.
On-premises::
Mule runtime that runs on a computer in your organization.
Payload::
The message content, which can be text, JSON, or CSV (comma-separated values).
Point-to-Point::
A pattern that allows an app to send a message that only a single app can receive.
Pub/Sub (Publish/Subscribe)::
A pattern that distributes messages to multiple consumers.
Publisher::
An app that sends messages to Anypoint MQ.
Queue::
A point-to-point message storage area that holds a message that a client receives.
+
For information, see xref:mq-queues.adoc[].
Subscriber::
An app that receives messages from Anypoint MQ.
[[message-ttl]]
TTL (time-to-live)::
+
Each queue has a message time-to-live (TTL).
TTL specifies how long the message is in the queue before Anypoint MQ expires the message and removes it from the queue.
+
include::partial$mq-ttl.adoc[tag=msgTTLchange]

== See Also

* xref:mq-index.adoc[]
* xref:mq-faq.adoc[]
