= Retrieving Usage Metrics Using Anypoint APIs

Depending on your control plane, you use different APIs to retrieve Anypoint MQ usage metrics.

[%header,cols="15,15,30"]
|===
| Control Plane | API | More Information
| https://anypoint.mulesoft.com/[US Cloud] | Anypoint MQ Stats | <<retrieve-metrics-mq-stats-api>>
| https://eu1.anypoint.mulesoft.com/[EU Cloud] | Anypoint MQ Stats | <<retrieve-metrics-mq-stats-api>>
| https://ca1.platform.mulesoft.com/monitoring[Canada Cloud] (Hyperforce)| Metering API | <<retrieve-metrics-metering-api>>
| https://jp1.platform.mulesoft.com/monitoring[Japan Cloud] (Hyperforce) | Metering API | <<retrieve-metrics-metering-api>>
|===


[[retrieve-metrics-mq-stats-api]]
== Retrieve Usage Metrics Using Anypoint MQ Stats API

To retrieve Anypoint MQ usage metrics on US Cloud or EU Cloud,
use the Anypoint MQ Stats API:

* xref:mq-apis.adoc#usage-by-env[Get Usage Metrics by Environment]
* xref:mq-apis.adoc#usage-by-org[Get Usage Metrics by Organization]

[NOTE]
include::partial$mq-faq.adoc[tag=apiStatsRequests]

[[retrieve-metrics-metering-api]]
== Retrieve Usage Metrics Using Anypoint Metering Query API

[NOTE]
These REST APIs are supported on 
https://ca1.platform.mulesoft.com/[Canada Cloud] and 
https://ja1.platform.mulesoft.com/[Japan Clouds] (Hyperforce) only.

To retrieve Anypoint MQ usage metrics on Canada Cloud or Japan Cloud, use the Metering Query API:

* <<get-api-req-root-org>>
* <<get-api-req-org-id>>
* <<get-api-req-org-env-id>>
* <<get-message-units-root-org>>
* <<get-message-units-org-id>>
* <<get-message-units-org-env-id>>

=== Before You Begin

* xref:mq-apis.adoc#get-bearer-token[Get a bearer token] for an Anypoint Platform user account that has the Usage Viewer permission for your root organization.
* Familiarize yourself with how Anypoint MQ uses xref:mq-usage.adoc[API requests and message units].
* Use the information in this table to construct your queries:
+
[%header,cols="15,45a"]
|===
| Parameter | Description
| TIMESERIES | How to group the output:

* Monthly: `P1M`
* Daily: `P1D`
* Hourly: `PT1H`

| BETWEEN  | Time frame to retrieve metrics for (timestamp specified in https://currentmillis.com/[milliseconds]).
| INSTANCE | Anypoint Platform instance:

* Canada Cloud: https://ca1.platform.mulesoft.com/metering/usage
* Japan Cloud: https://jp1.platform.mulesoft.com/metering/usage
|===


[[get-api-req-root-org]]
=== Get API Requests by Root Org

Use a command like this:

[source,bash,linenums]
----
curl --location '<INSTANCE>/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT api_requests FROM anypoint_mq_api_requests_count WHERE timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T12:00:53.577174248Z"
   },
   "data":[
      {
         "api_requests":100000.0,
         "timestamp":1730419200000
      }
   ]
}
----


[[get-api-req-org-id]]
=== Get API Requests for a Specific Org ID

Use a command like this:

[source,bash,linenums]
----
$ curl --location '<INSTANCE>/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT org_id, api_requests FROM anypoint_mq_api_requests_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T12:16:38.432741846Z"
   },
   "data":[
      {
         "org_id":"66310c16-bce5-43c4-b978-5945ed2f99c5",
         "api_requests":50000.0,
         "timestamp":1730419200000
      }
   ]
}
----

[[get-api-req-org-env-id]]
=== Get API Requests for a Specific Org and Environment

Use a command like this:

[source,bash,linenums]
----
curl --location '<INSTANCE>/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT org_id, env_id, api_requests FROM anypoint_mq_api_requests_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND env_id = '\''40eeb638-348c-4d80-9db6-7baf88b2d28f'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
curl --location '<INSTANCE>/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT org_id, env_id, api_requests FROM anypoint_mq_api_requests_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND env_id = '\''40eeb638-348c-4d80-9db6-7baf88b2d28f'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----


[[get-message-units-root-org]]
=== Get Message Units by Root Org

Use a command like this:

[source,bash,linenums]
----
curl --location '<INSTANCE>/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT message_units FROM anypoint_mq_message_units_count WHERE timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T12:04:34.195195241Z"
   },
   "data":[
      {
         "message_units":200000.0,
         "timestamp":1730419200000
      }
   ]
}
----

[[get-message-units-org-id]]
=== Get Message Units for a Specific Org ID

Use a command like this:

[source,bash,linenums]
----
curl --location '<INSTANCE>/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT org_id, message_units FROM anypoint_mq_message_units_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T12:18:43.124633917Z"
   },
   "data":[
      {
         "message_units":100000.0,
         "org_id":"66310c16-bce5-43c4-b978-5945ed2f99c5",
         "timestamp":1730419200000
      }
   ]
}
----

[[get-message-units-org-env-id]]
=== Get Message Units for a Specific Org ID and Environment ID

Use a command like this:

[source,bash,linenums]
----
$ curl --location '<INSTANCE>/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT org_id, env_id, message_units FROM anypoint_mq_message_units_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND env_id = '\''40eeb638-348c-4d80-9db6-7baf88b2d28f'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T13:00:37.519794881Z"
   },
   "data":[
      {
         "message_units":50000.0,
         "env_id":"40eeb638-348c-4d80-9db6-7baf88b2d28f",
         "org_id":"66310c16-bce5-43c4-b978-5945ed2f99c5",
         "timestamp":1730419200000
      }
   ]
}
----

== See Also

* xref:mq-faq.adoc#regions[Anypoint MQ Regions]
* xref:mq-apis.adoc#mq-stats-api[Anypoint MQ Stats API]
* xref:mq-faq.adoc#regions[Anypoint MQ Regions]
* Placeholder link to the OSv2 on HF topic
* Placeholder for Anypoint Metering API
