// tag::mqStatsAPIlimits[]
====
The Anypoint MQ Stats API limits retrieving stats for the
https://dev-portal.mulesoft.com/apis/anypoint-mq-stats.html[`/organizations/{ORGANIZATION_ID}`^] and
https://dev-portal.mulesoft.com/apis/anypoint-mq-stats.html[`/organizations/{ORGANIZATION_ID}/environments/{ENVIRONMENT_ID}`^] endpoints to 10 transactions per minute (TPM).

If the requests exceed this limit, the Anypoint MQ Stats API returns an HTTP 429 status code.

For all other https://dev-portal.mulesoft.com/apis/anypoint-mq-stats.html[Anypoint MQ Stats API^] endpoints, the limit is 200 transactions per minute.
====
// end::mqStatsAPIlimits[]

//tag::urlEncoded[]
The query parameters must be URL-encoded to preserve their values.
For example, you must URL-encode a `startDate` of `2024-07-11T17:51:54.000Z` to
`2024-07-11T17%3A51%3A54.000Z` before sending it in the query.
//end::urlEncoded[]

//tag::urlEncodedExample[]
To include a query string in the URL, you must encode spaces as "+", commas as "%2C", and colons as "%3A".

For example, for this decoded value:

`startDate=Sun, 25 Sep 2022 23:35:01 GMT&endDate=Wed, 25 Sep 2024 23:35:01 GMT&period=1month`

The encoded string is:

`startDate=Sun%2C+25+Sep+2022+23%3A35%3A01+GMT&endDate=Wed%2C+25+Sep+2024+23%3A35%3A01+GMT&period=1month`
//end::urlEncodedExample[]
