
// tag::mqPermsScopes[]
View clients::
View all client apps, as well as the client app IDs and client secrets for each client app.
View destinations::
View all destinations and each destination's settings (*ID*, *Type*, *Message TTL*, and *Message Lock Default TTL*), and view *In Queue* messages and *In Flight* message stats.
Clear destinations::
Same privileges as *View destinations*, plus permission to purge messages.
Manage clients::
Same privileges as *View clients*, plus permission to create client apps.
Administer destinations::
Same privileges as *View destinations* and *Clear destinations*, plus permission to:
+
** Create new queues, message exchanges, and bindings.
** Edit existing queues, message exchanges, and bindings.
Manage destinations (deprecated)::
Same privileges as *View destinations* and *Clear destinations*, plus permission to:
+
** Create new queues and message exchanges.
** Edit existing queues and message exchange settings.
** Access *Message Sender* and *Browser* pages.
** Delete messages.
+
[NOTE]
====
This permission is deprecated. 
To achieve the same abilities as *Manage permissions*, assign these permissions to the user:

** *Administer destinations* 
** *Destination subscriber for given environment*
** *Destination publisher for given environment*
====
Destination subscriber for given environment::
+
** Consume messages from a destination.
** Delete messages from a destination.

Destination publisher for given environment::
+
** Send messages to a destination.
** Update message TTL on a destination.
// end::mqPermsScopes[]


// tag::mqConnAppEndpointSupport[]
The `/authorize` endpoints in the Anypoint MQ Admin API and Anypoint MQ Broker API do not support Connected Apps.
You can't use tokens obtained from those endpoints to access a Connected App.
// end::mqConnAppEndpointSupport[]
